eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      dialect: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3309/test1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: S3cret
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
